TARGETS=array_bounds_check vector_bounds_check

CXXFLAGS=-std=c++11

.SUFFIXES: .cpp

%.o: %.cpp
	- @echo $(CXX) $(EXTRA_CFLAGS) $(CFLAGS) -c -o $@ $<
	- @$(CXX) $(EXTRA_CFLAGS) $(CFLAGS) -c -o $@ $<

all: $(TARGETS)

clobber:
	rm -f *.o
	rm -f $(TARGETS)

clean:
	rm -f *.o
